encoding: UTF-8

title: Places to Work
description: A collaborative collection of places to work in various cities
repo: https://github.com/pqvst/places-to-work

exclude:
  - .git/
  - Gemfile
  - Gemfile.lock
  - README.md
  - CNAME
  - node_modules
  - scripts
  - package-lock.json
  - package.json
  - serve.sh

collections:
  cities:
    output: true

plugins: 
  - jekyll-redirect-from
