version: '3'

services:
  app:
    build: .
    environment:
      - ROLLBAR_ACCESS_TOKEN=${ROLLBAR_ACCESS_TOKEN}
      - NODE_ENV=production
    volumes:
      - ./images:/usr/src/app/images
    labels:
      - traefik.enable=true
      - traefik.http.routers.cafeandcowork.rule=Host(`cafeandcowork.com`)
    logging:
      options:
        max-file: "10"
        max-size: "10m"
    restart: always
 
networks:
  default:
    name: router_default
    external: true
