version: '3'

services:
  app:
    build: .
    environment:
      - VIRTUAL_HOST=cafeandcowork.com
      - ROLLBAR_ACCESS_TOKEN=${ROLLBAR_ACCESS_TOKEN}
      - NODE_ENV=production
    volumes:
      - ./images:/usr/src/app/images
    logging:
      options:
        max-file: "10"
        max-size: "10m"
    restart: always
 
networks:
  default:
    external:
      name: router_default